### ISSUE TITLE
error in one of the examples due to change in hdf5r

### ISSUE THREAD

**Issue by hhoeflin** [ycli1995/hdf5r.Extra#1]
Hi,

Due to a bug report about writing attributes of length 0 in hdf5r (see https://github.com/hhoeflin/hdf5r/issues/208), attributes with length 0 can now be written and are returned as vectors of length 0 with the  correct type. 

This change causes a reverse dependency error in your examples:

```
Changes to worse in reverse depends:

Package: hdf5r.Extra
Check: examples
New result: ERROR
  Running examples in ‘hdf5r.Extra-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: H5-attributs
  > ### Title: Manipulate HDF5 attributes
  > ### Aliases: H5-attributs h5Attr h5Attributes h5AttrNames h5DeleteAttr
  > ###   h5WriteAttr h5Attr.H5D h5Attr.H5Group h5Attr.H5File h5Attr.character
  > ###   h5AttrNames.H5D h5AttrNames.H5Group h5AttrNames.H5File
  > ###   h5AttrNames.character h5Attributes.H5D h5Attributes.H5Group
  > ###   h5Attributes.H5File h5Attributes.character h5WriteAttr.H5D
  > ###   h5WriteAttr.H5Group h5WriteAttr.H5File h5WriteAttr.character
  > ###   h5DeleteAttr.H5D h5DeleteAttr.H5Group h5DeleteAttr.H5File
  > ###   h5DeleteAttr.character
  > 
  > ### ** Examples
  > 
  > file <- system.file("extdata", "pbmc_small.h5ad", package = "hdf5r.Extra")
  > 
  > # Read H5 attribute
  > x <- h5Attr(file, "encoding-version")
  > x <- h5Attr(file, "column-order", "raw/var") ## An empty attribute
  > stopifnot(is.null(x))
  Error: is.null(x) is not TRUE
  Execution halted
```

I tested it, and the reason for the error is that now a `numeric(0)` is being returned instead of a `NULL`. Would you mind changing the examples failing (e.g. `stopifnot(is.null(x) || length(x) == 0)`) or something like that.

Thanks

**Comment by hhoeflin** [comment]
You can check the proposed changed code in this branch:

https://github.com/hhoeflin/hdf5r/tree/bug/fix_empty_attrs_again

**Comment by ycli1995** [comment]
Hi, @hhoeflin . Sorry for the delay, I've submitted an updated `hdf5r.Extra` to CRAN which should fix the example.
Thanks.
